"""empty message

Revision ID: 561ca9b9b5c1
Revises: 4230103605c0
Create Date: 2021-05-23 00:55:09.243689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '561ca9b9b5c1'
down_revision = '4230103605c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
